<?php
/* This are the vars you may need to modify */
/* Some may be placed in conf files */
/* Some may be generated by your application */
//$text = ""; // May depend of your application context

$text = file_get_contents("../data/example.html");
$configxml = simplexml_load_file("../../config/config.xml");
$apikey = (string)$configxml->apis->zemanta->apikey;
$url = (string)$configxml->apis->zemanta->url;



if (isset($_GET['url'])) {
    $url = $_GET['url'];
} else {
    $url = "http://news.google.com/news/url?sa=t&fd=R&usg=AFQjCNEDrgL2u-EM3leLDxFQMgLbZo4vKA&url=http://abcnews.go.com/Sports/wireStory/ryan-throws-td-passes-falcons-rout-giants-34-17992741";
}
print_r($url);
$content = file_get_contents($url);



$method = "zemanta.suggest"; // May depend of your application context
/* It is esayer to deal with arrays */
$args = array(
'method'=> $method,
'api_key'=> $apikey,
'text'=> $content,
'format'=> $format,
'return_images' => 0,
'return_articles' => 0,
'return_categories' => 1
);

/* Here we build the data we want to POST to Zementa */
$data = "";
foreach($args as $key=>$value)
{
$data .= ($data != "")?"&":"";
$data .= urlencode($key)."=".urlencode($value);
}

/* Here we build the POST request */
$params = array('http' => array(
'method' => 'POST',
'Content-type'=> 'application/x-www-form-urlencoded',
'Content-length' =>strlen( $data ),
'content' => $data
));

/* Here we send the post request */
$ctx = stream_context_create($params); // We build the POST context of the* request
$fp = @fopen($url, 'rb', false, $ctx); // We open a stream and send the request
if ($fp)
{
/* Finaly, herewe get the response of Zementa */
$response = @stream_get_contents($fp);
if ($response === false)
{
$response = "Problem reading data from ".$url.", ".$php_errormsg;
}
fclose($fp); // We close the stream
}
else
{
$response = "Problem reading data from ".$url.", ".$php_errormsg;
}


print_r($response);

return;
$xml = new SimpleXMLElement($response);

$responseArray = $xml->xpath("//keyword");
print_r($responseArray);

$responseArray = $xml->xpath("//categories");
print_r($responseArray);


?>